// <auto-generated />
using System;
using EconomIA.Adapters.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EconomIA.Adapters.Persistence.Migrations
{
    [DbContext(typeof(EconomIACommandDbContext))]
    [Migration("20260102200000_CriarTabelaOrgaoMonitorado")]
    partial class CriarTabelaOrgaoMonitorado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EconomIA.Domain.Ata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnoAta")
                        .HasColumnType("integer")
                        .HasColumnName("ano_ata");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<bool>("Cancelado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelado");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_assinatura");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataAtualizacaoGlobal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_global");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cancelamento");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao");

                    b.Property<DateTime?>("DataPublicacaoPncp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao_pncp");

                    b.Property<long>("IdentificadorDoOrgao")
                        .HasColumnType("bigint")
                        .HasColumnName("identificador_do_orgao");

                    b.Property<string>("NumeroAtaRegistroPreco")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_ata_registro_preco");

                    b.Property<string>("NumeroControlePncpAta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_controle_pncp_ata");

                    b.Property<string>("NumeroControlePncpCompra")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_controle_pncp_compra");

                    b.Property<string>("ObjetoContratacao")
                        .HasColumnType("text")
                        .HasColumnName("objeto_contratacao");

                    b.Property<string>("Usuario")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario");

                    b.Property<DateTime?>("VigenciaFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateTime?>("VigenciaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id")
                        .HasName("pk_ata");

                    b.HasIndex("AnoAta")
                        .HasDatabaseName("ix_ata_AnoAta");

                    b.HasIndex("IdentificadorDoOrgao")
                        .HasDatabaseName("ix_ata_IdentificadorDoOrgao");

                    b.HasIndex("NumeroControlePncpAta")
                        .IsUnique()
                        .HasDatabaseName("un_ata_NumeroControlePncpAta");

                    b.HasIndex("NumeroControlePncpCompra")
                        .HasDatabaseName("ix_ata_NumeroControlePncpCompra");

                    b.ToTable("ata", (string)null);
                });

            modelBuilder.Entity("EconomIA.Domain.OrgaoMonitorado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<long>("IdentificadorDoOrgao")
                        .HasColumnType("bigint")
                        .HasColumnName("identificador_do_orgao");

                    b.HasKey("Id")
                        .HasName("pk_orgao_monitorado");

                    b.HasIndex("IdentificadorDoOrgao")
                        .IsUnique()
                        .HasDatabaseName("un_orgao_monitorado_identificador_do_orgao");

                    b.ToTable("orgao_monitorado", (string)null);
                });

            // Remaining entities omitted for brevity - same as snapshot
#pragma warning restore 612, 618
        }
    }
}
