// <auto-generated />
using System;
using EconomIA.Adapters.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EconomIA.Adapters.Persistence.Migrations
{
    [DbContext(typeof(EconomIACommandDbContext))]
    [Migration("20260106180000_AdicionarParametrosExecucao")]
    partial class AdicionarParametrosExecucao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EconomIA.Domain.ExecucaoCarga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<long?>("DuracaoTotalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duracao_total_ms");

                    b.Property<DateTime?>("FimEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim_em");

                    b.Property<string>("Hostname")
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<DateTime?>("InicioEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_em");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("text")
                        .HasColumnName("mensagem_erro");

                    b.Property<string>("ModoExecucao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modo_execucao");

                    b.Property<string>("ParametrosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parametros");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TipoGatilho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_gatilho");

                    b.Property<int>("TotalAtasProcessadas")
                        .HasColumnType("integer")
                        .HasColumnName("total_atas_processadas");

                    b.Property<int>("TotalComprasProcessadas")
                        .HasColumnType("integer")
                        .HasColumnName("total_compras_processadas");

                    b.Property<int>("TotalContratosProcessados")
                        .HasColumnType("integer")
                        .HasColumnName("total_contratos_processados");

                    b.Property<int>("TotalItensIndexados")
                        .HasColumnType("integer")
                        .HasColumnName("total_itens_indexados");

                    b.Property<int>("TotalOrgaosComErro")
                        .HasColumnType("integer")
                        .HasColumnName("total_orgaos_com_erro");

                    b.Property<int>("TotalOrgaosProcessados")
                        .HasColumnType("integer")
                        .HasColumnName("total_orgaos_processados");

                    b.Property<string>("VersaoAplicacao")
                        .HasColumnType("text")
                        .HasColumnName("versao_aplicacao");

                    b.HasKey("Id")
                        .HasName("pk_execucao_carga");

                    b.ToTable("execucao_carga", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
